### ISSUE TITLE
Difference between py3 and py2 range

### ISSUE THREAD

**Issue by steven-albanese** [choderalab/sams#5]
Raising an issue here in response to the problems discussed on slack. In python 3, range() returns an object instead of a list as in python 2. It was suggested that wrapping `range(n)` with `set()` might be a solution.

**Comment by jchodera** [comment]
Can you paste the actual error traceback?

**Comment by steven-albanese** [comment]
```
Creating mTOR test system...
Adding solvent...
Creating system...
Creating alchemically-modified system...
Setting up alchemical intermediates...
Minimizing...
Initial energy is 2839989740.958 kcal/mol
Final energy is   -2017700.724 kcal/mol
Energy after iteration 0 of 50 steps : -1781661.8193499462
Energy after iteration 1 of 50 steps : -1751115.8192090795
Energy after iteration 2 of 50 steps : -1736361.4509029489
Energy after iteration 3 of 50 steps : -1726296.0847334915
Energy after iteration 4 of 50 steps : -1717720.3379098552
Energy after iteration 5 of 50 steps : -1711414.8348110516
Energy after iteration 6 of 50 steps : -1706554.395462627
Energy after iteration 7 of 50 steps : -1701041.0893581186
Energy after iteration 8 of 50 steps : -1698313.8181279073
Energy after iteration 9 of 50 steps : -1695063.8868308722
Setting up samplers...
================================================================================
SAMS sampler iteration     0
--------------------------------------------------------------------------------
Expanded Ensemble sampler iteration        0
................................................................................
MCMC sampler iteration 0
Final energy is -2774501.601 kT
elapsed time   36.908 s
................................................................................
Writing frame...
Traceback (most recent call last):
  File "AlchemicalLoopSoftening.py", line 160, in <module>
    system.sams_sampler.run(niterations)
  File "/cbio/jclab/home/albaness/miniconda3/lib/python3.5/site-packages/sams-0.1-py3.5.egg/sams/samplers.py", line 1065, in run
    self.update()
  File "/cbio/jclab/home/albaness/miniconda3/lib/python3.5/site-packages/sams-0.1-py3.5.egg/sams/samplers.py", line 1030, in update
    self.update_sampler()
  File "/cbio/jclab/home/albaness/miniconda3/lib/python3.5/site-packages/sams-0.1-py3.5.egg/sams/samplers.py", line 935, in update_sampler
    self.sampler.update()
  File "/cbio/jclab/home/albaness/miniconda3/lib/python3.5/site-packages/sams-0.1-py3.5.egg/sams/samplers.py", line 790, in update
    self.update_state()
  File "/cbio/jclab/home/albaness/miniconda3/lib/python3.5/site-packages/sams-0.1-py3.5.egg/sams/samplers.py", line 705, in update_state
    neighborhood.remove(current_state_index) # remove current state
AttributeError: 'range' object has no attribute 'remove'
Set compute mode to DEFAULT for GPU 0000:03:00.0.
```

**Comment by steven-albanese** [comment]
To follow up on this, I added `from past.builtins import range` to `samplers.py`, which should make the code compatible with both py2 and py3. It just adds the `future` module to the list of dependencies. It's conda installable, so it might be a nice fix? I'm not sure what your thoughts are on this

**Comment by jchodera** [comment]
Isn't the fix for this just to wrap `range()` in `set()` in one or two places?  Can we just fix that instead of bringing in another dependency?

**Comment by steven-albanese** [comment]
yeah, I can try that. I thought this might be a less intrusive solution, but it should be simple enough to change back

**Comment by jchodera** [comment]
Is this resolved, @steven-albanese?
